blogrecetas/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from blogrecetas.views import Index, Contacto,AboutUs 
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name = 'index'),
    path('contacto/', Contacto.as_view(), name = 'contacto'),
    path('recetas/', include('recetas.urls', namespace = 'recetas')),
    path('about_us/', AboutUs.as_view(), name = 'about_us'),
    re_path('usuarios/', include('users.urls', namespace = 'users_app')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

recetas/urls.py
from django.urls import path
from .views import *

app_name = 'recetas'

urlpatterns = [
    path('buscar-receta/', buscar_receta, name = 'buscar_receta'),
    path('', ListaRecetas.as_view(), name = 'lista_recetas'),
    path('crear-receta/', CrearReceta.as_view(), name='crear_receta'),
    path('detail-receta/<int:pk>/', DetailReceta.as_view(), name='detail_receta'),
    path('eliminar-receta/<int:pk>/', EliminarReceta.as_view(), name='eliminar_receta'),
    path('actualizar-receta/<int:pk>/', ActualizarReceta.as_view(), name='actualizar_receta'),
]

users/urls.py
from django.urls import path
from . import views
from users.views import logout_view

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('panel/', views.PanelPage.as_view(), name='user_panel'),
    path('login/', views.LoginUser.as_view(), name='user_login'),
    path('logout/', logout_view, name='user_logout'),
    path('update/', views.UpdatePasswordView.as_view(), name='user_update'),
    
]

recetas/models.py
from django.db import models

# Create your models here.

class Receta(models.Model):
    nombre = models.CharField(max_length = 30)
    tipo = models.CharField(max_length = 30)
    porciones = models.FloatField(default = 0)
    ing_y_cant = models.CharField(max_length = 30)
    procedimiento = models.CharField(max_length = 30)
    is_active = models.BooleanField(default = True)
    image_recetas = models.ImageField(upload_to = 'image_recetas', blank = True , null = True)

    class Meta:
        verbose_name = 'receta'
        verbose_name_plural = 'recetas'

    def __str__(self):
        return self.nombre

recetas/forms.py
from turtle import width
from django import forms
from .models import Receta

class FormCrearReceta(forms.ModelForm):
    class Meta:
        model = Receta
        fields = '__all__'

recetas/views.py
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponse
from recetas.models import Receta
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from recetas.forms import FormCrearReceta
from django.contrib.auth.mixins import LoginRequiredMixin

########################################################## CREATE VIEW ########################################################################

class CrearReceta(LoginRequiredMixin, CreateView):
    model = Receta
    form_class = FormCrearReceta 
    template_name = 'crear_receta.html'
    success_url = reverse_lazy('recetas:lista_recetas')
    login_url = reverse_lazy('users_app:user_login')


########################################################### LIST VIEW ########################################################################

class ListaRecetas(ListView):
    model = Receta
    template_name= 'recetas.html'
    queryset = Receta.objects.filter(is_active = True)
    
    def get_context_data(self):
        context = {}
        lista_recetas = Receta.objects.all()
        context['lista_recetas'] = lista_recetas
        return context


########################################################### DETAIL VIEW ######################################################################

class DetailReceta(DetailView):
    model = Receta
    template_name = 'detail_receta.html'
   

########################################################### DELETE VIEW ######################################################################

class EliminarReceta(LoginRequiredMixin, DeleteView):
    model = Receta
    template_name = 'eliminar_receta.html'
    login_url = reverse_lazy('users_app:user_login')

    def get_success_url(self):
        return reverse('recetas:lista_recetas')

########################################################### UPDATE VIEW ######################################################################


class ActualizarReceta(LoginRequiredMixin, UpdateView):
    model = Receta
    template_name = 'actualizar_receta.html'
    fields = '__all__'
    login_url = reverse_lazy('users_app:user_login')

    def get_success_url(self):
        return reverse('recetas:detail_receta', kwargs = {'pk':self.object.pk})


########################################################### FUNCION BUSCAR ######################################################################


def buscar_receta(request):
    recetas = Receta.objects.filter(nombre__icontains=request.GET['search'])
    if recetas.exists():
        context = {'recetas':recetas}
    else:
        context = {'errors':'No se encontro el producto'}
    return render(request, 'buscar_receta.html', context = context)

templates/about_us.html
{% extends 'base.html' %}

{% block titulo %} Sobre Nosotros {% endblock %}

{% block contenido %}
        <!-- Testimonials-->
        <section class="testimonials text-center bg-light">
            <div class="container">
                <h2 class="mb-5">Sobre nosotros</h2>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                            
                            <h5>Lucio Rostagno</h5>
                            <p class="font-weight-light mb-0">Hola, yo soy Lucio y junto a Lucía cree la base de este proyecto. Además colaboré con los formularios de algunos templates.</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                            
                            <h5>Lucía Molina</h5>
                            <p class="font-weight-light mb-0">Hola! Mi nombre es Lucía, como estudiante de programación con Phyton y Django coordiné la realización de esta web, creando la app base, asi como integrando y mejorando el trabajo de mis compañeros. Esto incluyó la integración de las imágenes tanto para las recetas como para los usuarios, entre otros.</p>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="testimonial-item mx-auto mb-5 mb-lg-0">
                            
                            <h5> Manuel León Robles</h5>
                            <p class="font-weight-light mb-0">Hola que tal, soy estudiante de programación backend python-django. Algunos de mis labores realizadas en esta pagina web fue la gestion de usuarios, tambien parte de CRUD y el sistema de busqueda</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Call to Action-->
        {% endblock contenido %}

templates/actualizar_receta.html
{% extends 'base.html' %}

{% block titulo %} ACTUALIZAR RECETA {% endblock titulo %}

{% block contenido %}


{% if form %}
<h2 style="margin-left:30rem">Complete los campos a actualizar</h2>
<form action="" method="POST" style="margin-left:40rem;margin-top:7rem">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" class="btn btn-primary" value="Guardar">
    <a class="btn btn-primary" href="/recetas/">Regresar</a>
</form>
{% endif %}


{% endblock contenido %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block titulo %}{% endblock titulo %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
            integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar " style="background: lightblue;">
            <a class="navbar-brand" href="/">Inicio</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/about_us/"> Sobre Nosotros <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/contacto/">Contacto <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/recetas/">Recetas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/recetas/crear-receta/">Crear Receta</a>
                    </li>   
                    <li class="nav-item">             
                        <a style="margin-left: 45rem;" class="nav-link" href="{% url 'users_app:user_register' %}">Registrarse</a>
                    </li>                
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users_app:user_panel' %}">Panel de Usuario</a> 
                        </li>                
                    

                </ul>
                </form>
            </div>
        
        </nav>
    
        
        
        {% block contenido %}
        {% endblock contenido %}
    
    </body>
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>
    
    </html>

templates/buscar_receta.html
{% extends 'base.html' %}

{% block titulo %} BUSCAR RECETA {% endblock %}

{% block contenido %}

<h1 style="margin-left:30rem">Aca va el contenido de las recetas</h1>

<a style="margin-left: 8rem;" class="btn btn-primary" href="/recetas/">Regresar</a>

{% if recetas %}
    <div class="d-flex" style="margin-top:5rem; margin-left:7rem">
        {% for receta in recetas %}
            
            <div class="d-flex" style="margin-top:5rem; margin-left:7rem">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        {% if receta.image_recetas %}
                         <img src="{{receta.image_recetas.url}}" class="card-img-top" >
                        {% endif %} 
                        <h5 class="card-title">{{receta.nombre}}</h5>
                        <p class="card-text">{{receta.tipo}}</p>
                        <p class="card-text">{{receta.ing_y_cant}}</p>
                        <p class="card-text">{{receta.procedimiento}}</p>
                        <a href="/recetas/detail-receta/{{receta.id}}/" class="btn btn-primary">Ver mas!</a>
                    </div>
                </div>
            </div>
        
        {% endfor %}
    </div>
{% endif %}


<div style = "color:red; margin-left:25rem">{{errors}}</div>

{% endblock %}

templates/contacto.html
{% extends 'base.html' %}

{% block titulo %}
    Contacto
{% endblock %}

{% block contenido %}
<header id="head" class="secondary"></header>

<!-- container -->
<div class="container">

    <div class="row">
        
        <!-- Article main content -->
        <article class="col-sm-9 maincontent">
            <header class="page-header">
                <h1 class="page-title">Contactenos</h1>
                <h4> elblogderecetas@soporte.com</h4>
                <h2>+54 9 11 45678903</h2>

            </header>
            <br>
                <form>
                    <div class="row">
                        <div class="col-sm-4">
                            <input class="form-control" type="text" placeholder="Nombre">
                        </div>
                        <div class="col-sm-4">
                            <input class="form-control" type="text" placeholder="Email">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-12">
                            <textarea placeholder="Escriba su mensaje..." class="form-control" rows="9"></textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-sm-10 text-right">
                            <input class="btn btn-action" type="submit" value="Enviar">
                        </div>
                    </div>
                </form>

        </article>
        <!-- /Article -->
        {% endblock contenido %}

templates/crear_receta.html
{% extends 'base.html' %}

{% block titulo %} CREAR RECETA {% endblock titulo %}

{% block contenido %}

{% if form %}
<h1>Completa el formulario para crear tu receta! </h1>
<h2 style="margin-left:30rem">Complete los campos de la nueva receta</h2>
<form action="" method="POST" style="margin-left:40rem;margin-top:7rem" enctype ="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" , value="Enviar">
</form>
{% endif %}

{% endblock contenido %}

templates/detail_receta.html
{% extends 'base.html' %}

{% block titulo %} DATOS DE RECETA {% endblock titulo %}

{% block contenido %}


<h1 style="margin-left:30rem">Detalles de las recetas</h1>

<a style="margin-left: 8rem;" class="btn btn-primary" href="/recetas/">Regresar</a>

<div class="d-flex" style="margin-top:5rem; margin-left:7rem">

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            {% if receta.image_recetas %}
            <img src="{{receta.image_recetas.url}}" class="card-img-top" >
            {% endif %}   
            <h4 class="card-title">{{object.nombre}}</h4>
            <h5>Tipo de receta</h5>
            <p class="card-text">{{object.tipo}}</p>
            <h5>Ingredientes</h5>
            <p class="card-text">{{object.ing_y_cant}} </p>
            <h5>Paso a paso</h5>
            <p class="card-text">{{object.procedimiento}}</p>
            <a href="/recetas/actualizar-receta/{{object.id}}/" class="btn btn-primary">Editar</a>
            <a href="/recetas/eliminar-receta/{{object.id}}/" class="btn btn-danger">Eliminar</a>
        </div>
    </div>

</div>


{% endblock contenido %}

templates/eliminar_receta.html
{% extends 'base.html' %}

{% block titulo %} ELIMINAR RECETA {% endblock titulo %}

{% block contenido %}


<h3 style="color: red">Estas por eliminar esta receta: {{object.nombre}}, ¿Seguro que desea eliminar?</h3>

<form method = "POST">
    {% csrf_token %}
    <button class="btn btn-danger" type="submit">Eliminar</button>
    <a class="btn btn-primary" href="/recetas/">Regresar</a>
</form>


{% endblock contenido %}

templates/index.html
{% extends 'base.html' %}

{% block titulo %}
INICIO
{% endblock %}

{% block contenido %}
<h1>¡Bienvenido a nuestra web de recetas!</h1>
<h3>Registrate para poder crear las tuyas</h3>
{% endblock %}

templates/recetas.html
{% extends 'base.html' %}

{% block titulo %} LISTA DE RECETAS {% endblock titulo %}

{% block contenido %}
<h1> Recetas </h1>

<form style="margin-left: 50rem;" class="form-inline my-2 my-lg-0" action = "/recetas/buscar-receta/" method = "GET">
    <input class="form-control mr-sm-2" type="text" placeholder="Buscar" aria-label="Search" name = 'search'>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>


<div class="d-flex" style="margin-top:3rem; margin-left:7rem; margin-bottom:3rem;">
    {% for receta in lista_recetas %}

    
    <div class="card" style="width: 18rem;">
        {% if receta.image_recetas %}
        <img src="{{receta.image_recetas.url}}" class="card-img-top" >
        {% endif %}    
        <div class="card-body">
            <h5 class="card-title">{{receta.nombre}}</h5>
            <p class="card-text">{{receta.procedimiento}}</p>
            <a href="/recetas/detail-receta/{{receta.id}}/" class="btn btn-primary">Ver mas!</a>
        </div>
    </div>

    {% endfor %}

</div>

{% endblock contenido %}