blogrecetas/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from blogrecetas.views import Index, Contacto,AboutUs 
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name = 'index'),
    path('contacto/', Contacto.as_view(), name = 'contacto'),
    path('recetas/', include('recetas.urls', namespace = 'recetas')),
    path('about_us/', AboutUs.as_view(), name = 'about_us'),
    re_path('usuarios/', include('users.urls', namespace = 'users_app')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from users.views import logout_view

app_name = "users_app"

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('panel/', views.PanelPage.as_view(), name='user_panel'),
    path('login/', views.LoginUser.as_view(), name='user_login'),
    path('logout/', logout_view, name='user_logout'),
    path('update/', views.UpdatePasswordView.as_view(), name='user_update'),
    
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    username = models.CharField(max_length=10, unique=True)
    email = models.EmailField()
    nombres = models.CharField(max_length=30, blank=True)
    apellidos = models.CharField(max_length=30, blank=True)
    genero = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    codregistro = models.CharField(max_length=6, blank=True)
    image_user = models.ImageField(upload_to = 'image_user', blank = True , null = True)
    link = models.CharField(max_length=300, blank=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email',]

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.nombres + ' ' + self.apellidos

users/forms.py
from django import forms
from .models import User
from django.contrib.auth import authenticate

class UserRegisterForm(forms.ModelForm):

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Repetir Contraseña'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Repetir Contraseña'
            }
        )
    )

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'nombres',
            'apellidos',
            'genero',
            'image_user',
            'link',
        )

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')

class LoginForm(forms.Form):

    username = forms.CharField(
        label='username',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder':'Username',
                'style': '{ margin: 10px }'
            }
        )
    )
    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Contraseña'
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')

        return self.cleaned_data


class UpdatePasswordForm(forms.Form):

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'nombres',
            'apellidos',
            'genero',
            'image_user',
            'link',
        )

    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Contraseña Actual'
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder':'Contraseña Nueva'
            }
        )
    )

users/views.py
from django.shortcuts import render, redirect
from django. urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect

from django.views.generic import TemplateView, View, CreateView
from django.views.generic.edit import FormView

from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserRegisterForm, LoginForm, UpdatePasswordForm
from users.models import User
   

class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = '/'

    def form_valid(self, form):

        User.objects.create_user(
            form.cleaned_data['username'],
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            nombres=form.cleaned_data['nombres'],
            apellidos=form.cleaned_data['apellidos'],
            genero=form.cleaned_data['genero'],
            image_user = form.cleaned_data['image_user'],
            link = form.cleaned_data['link']
                  )
                
        return super(UserRegisterView, self).form_valid(form)


class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('users_app:user_panel')

    def form_valid(self, form):
        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password'],
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


def logout_view(request):
    logout(request)
    return redirect('index')


class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/update.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user_login')
    login_url = reverse_lazy('users_app:user_login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            username = usuario.username,
            password = form.cleaned_data['password1']
        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()



            logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)


############################################ PANEL #############################################################


class PanelPage(LoginRequiredMixin, TemplateView):
    template_name = "users/panel.html"
    login_url = reverse_lazy('users_app:user_login')

templates/users/base_users.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block titulo %}{% endblock titulo %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
            integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar " style="background: lightblue;">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="navbar-brand" href="/">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a style="margin-left: 10rem;" class="nav-link" href="{% url 'users_app:user_login' %}">Iniciar Sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users_app:user_register' %}">Registrarse</a>
                    </li>
                </ul>
                </form>
            </div>
        </nav>
    
        
        
        {% block contenido %}
        {% endblock contenido %}
    
    </body>
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>
    
    </html>

templates/users/login.html
{% extends 'users/base_users.html' %}

{% block titulo %} LOGIN {% endblock titulo %}

{% block contenido %}


<h1 style="margin-top: 2rem; margin-left: 40rem; margin-bottom: 2rem;">Acceder al Sistema</h1>
<div style="margin-left: 41rem;">
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Acceder</button>
        <button type="submit">Volver</button>
    </form>
    <div class="row">
        <div class="col-lg-8">
            <b><a href="">Olvido su contraseña?</a></b>
        </div>
    </div>
</div>

{% endblock contenido %}

templates/users/login2.html
{% extends 'users/base_users.html' %}

{% block titulo %} LOGIN {% endblock titulo %}

{% block contenido %}

<div>
    <main class="img-fondo3">
        <div class="login-box">
            <img src="img/logo.png" class="avatar" alt="Avatar Image">
            <h1>Iniciar Sesión</h1>
            <form>{% csrf_token %}
                <!-- USERNAME INPUT -->
                <label for="username">Usuario</label>
                <input type="text" placeholder="Ingrese el Usuario">
                <!-- PASSWORD INPUT -->
                <label for="password">Contraseña</label>
                <input type="password" placeholder="Ingrese la Contraseña">
            </form>
            
            <input type="submit" value="Entrar" onclick="location.href='index.html'">
            <a href="#">¿Perdiste tu Contraseña?</a><br>
            <a href="#">¿No tienes una Cuenta?</a>

        </div>
    </main>

</div>

{% endblock contenido %}

templates/users/panel.html
{% extends 'base.html' %}

{% block titulo %} PANEL {% endblock titulo %}

{% block contenido %}


<h1 style="margin-top: 5rem; margin-left: 5rem;">Panel de Usuario</h1>
<div style="margin-left: 5rem;">
    {% if user.image_user %}
    <img src="{{user.image_user.url}}"  width="100" height="100" >
    {% endif %} 

    <h3 style="margin-bottom: 20px;">Bienvenido: {{user}}</h3>
      
<ul>
    <li><a href="{% url 'users_app:user_logout' %}">Cerrar Sesión</a></li>
    <li><a href="{% url 'users_app:user_update' %}">Actualizar Datos</a></li>

 </ul>
</div>



{% endblock contenido %}

templates/users/register.html
{% extends 'users/base_users.html' %}

{% block titulo %} REGISTRO DE USUARIO {% endblock titulo %}

{% block contenido %}

<h1 style="margin-top: 2rem; margin-left: 40rem; margin-bottom: 2rem;"> Registrar Nuevo Usuario</h1>
<div style="margin-left: 45rem;">
    <form action="" method="POST" enctype ="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>
        <button class="submit" type="submit">Volver</button> 
    </form>
</div>

{% endblock contenido %}

templates/users/update.html
{% extends 'base.html' %}

{% block titulo %} ACTUALIZACION DE USUARIO {% endblock titulo %}

{% block contenido %}

<h1 style="margin-top: 5rem; margin-left: 5rem;">Actualizar Usuario</h1>
<a style="margin-left: 5rem; margin-bottom: 20px;" class="btn seleccion_ch back disable-select" href="{% url 'users_app:user_panel' %}">Regresar</a>
<div style="margin-left: 5rem;">

    {% if user.image_user %}
    <img src="{{user.image_user.url}}"  width="100" height="100" >
    {% endif %} 

    <h3 style="margin-bottom: 20px;">Bienvenido: {{user}}</h3>
    <form action="" method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn seleccion save disable-select" style="margin-top: 20px;" type="submit">Guardar</button>
    </form>
    
</div>

{% endblock contenido %}